
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.1"

minimal_mistakes_skin: "air" # "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

include:
  - _pages
  
  
  # Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
  
  author:
    name: "Projects"
    bio: "Jump straight to any project or into various aspects of each"
    links:
      - label: "Ensemble Probabilistic Model"
      - url: 
