theme: "minimal-mistakes-jekyll"'
remote_theme: "mmistakes/minimal-mistakes@4.19.1"

plugins: jekyll-include-cache

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

