# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Experimental COVID-19 Propagation Models
email:
description:
color_scheme: "light"
search: true

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


include:
  - _models
  - _pages
  
  
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
  
author:
  name: "Projects"
  avatar:
  bio: "Jump straight to any project or into various aspects of each"
  links:
    - label: "Ensemble Probabilistic Model"
    - icon: "fas fa-fw fa-link"
    - url: "https://github.com/mwmckenzie/Experimental-COVID-19-Models/"

defaults:
  # _posts
  - scope:
      path: "_models"
      type: models
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
